plugins { id 'com.android.application' }
android {
 namespace 'pe.edu.senati.senatimap'
 compileSdk 35
 defaultConfig {
   applicationId 'pe.edu.senati.senatimap'
   minSdk 24
   targetSdk 35
   versionCode 9
   versionName '1.8-live-location'
 }
 compileOptions {
   sourceCompatibility JavaVersion.VERSION_17
   targetCompatibility JavaVersion.VERSION_17
 }
}
