package pe.edu.senati.senatimap;
import android.Manifest;import android.annotation.SuppressLint;import android.app.Activity;import android.content.pm.PackageManager;import android.location.*;import android.os.*;import android.webkit.*;import android.widget.Toast;import java.util.Locale;
public class MainActivity extends Activity{
 WebView w; static final int REQ=41;
 @SuppressLint({"SetJavaScriptEnabled","AddJavascriptInterface"}) public void onCreate(Bundle b){super.onCreate(b);w=new WebView(this);setContentView(w);WebSettings s=w.getSettings();s.setJavaScriptEnabled(true);s.setDomStorageEnabled(true);s.setAllowFileAccess(true);w.setWebViewClient(new WebViewClient());w.setWebChromeClient(new WebChromeClient());w.addJavascriptInterface(new Bridge(),"SenatiAndroid");w.loadUrl("file:///android_asset/index.html");}
 public class Bridge{@JavascriptInterface public void requestLocation(){runOnUiThread(()->requestLoc());}}
 void requestLoc(){if(checkSelfPermission(Manifest.permission.ACCESS_FINE_LOCATION)!=PackageManager.PERMISSION_GRANTED&&checkSelfPermission(Manifest.permission.ACCESS_COARSE_LOCATION)!=PackageManager.PERMISSION_GRANTED){requestPermissions(new String[]{Manifest.permission.ACCESS_FINE_LOCATION,Manifest.permission.ACCESS_COARSE_LOCATION},REQ);return;}locate();}
 @SuppressLint("MissingPermission") void locate(){LocationManager m=(LocationManager)getSystemService(LOCATION_SERVICE);Location best=null;try{Location a=m.getLastKnownLocation(LocationManager.GPS_PROVIDER),n=m.getLastKnownLocation(LocationManager.NETWORK_PROVIDER);best=a;if(n!=null&&(best==null||n.getTime()>best.getTime()))best=n;if(best!=null)push(best);LocationListener l=new LocationListener(){public void onLocationChanged(Location x){push(x);try{m.removeUpdates(this);}catch(Exception ignored){}}};if(m.isProviderEnabled(LocationManager.GPS_PROVIDER))m.requestSingleUpdate(LocationManager.GPS_PROVIDER,l,Looper.getMainLooper());else if(m.isProviderEnabled(LocationManager.NETWORK_PROVIDER))m.requestSingleUpdate(LocationManager.NETWORK_PROVIDER,l,Looper.getMainLooper());else Toast.makeText(this,"Activa la ubicación o usa Simular.",Toast.LENGTH_SHORT).show();}catch(Exception e){Toast.makeText(this,"Usa Simular ubicación.",Toast.LENGTH_SHORT).show();}}
 void push(Location x){String js=String.format(Locale.US,"SenatiMap.setUserLocation(%f,%f,%f,false)",x.getLatitude(),x.getLongitude(),x.getAccuracy());w.post(()->w.evaluateJavascript(js,null));}
 public void onRequestPermissionsResult(int r,String[] p,int[] g){super.onRequestPermissionsResult(r,p,g);if(r==REQ){for(int x:g)if(x==PackageManager.PERMISSION_GRANTED){locate();return;}Toast.makeText(this,"Permiso denegado. Usa Simular.",Toast.LENGTH_SHORT).show();}}
 @SuppressWarnings("deprecation") public void onBackPressed(){if(w.canGoBack())w.goBack();else super.onBackPressed();}
}
